#!/usr/bin/env python3
"""
NOTICE: This file was substantially generated by an LLM coding agent.

Generates a fold-it-yourself Blue Line notebook:

  blue-line-notebook.pdf          all pages in reading order (half-letter)
  blue-line-notebook-booklet.pdf  same pages imposed 2-up on letter landscape

Two dot-grid pages per CTA Blue Line stop, plus a front and back cover, so the
total page count is a multiple of 4 and folds as a single signature.

Requires: pdflatex (with fancyhdr, geometry, pdfpages, helvet, xcolor).
"""

import argparse
import csv
import shutil
import subprocess
import sys
from pathlib import Path

# --------------------------------------------------------------------------
# Paths and filenames
# --------------------------------------------------------------------------

HERE = Path(__file__).resolve().parent
STOPS_CSV = HERE.parent / "misc" / "cta-blue-line-stops.csv"
BUILD_DIRNAME = "_build"

MAIN_STEM = "blue-line-notebook"
BOOKLET_STEM = "blue-line-notebook-booklet"
MAIN_PDF = f"{MAIN_STEM}.pdf"
BOOKLET_PDF = f"{BOOKLET_STEM}.pdf"
MAIN_TEX = f"{MAIN_STEM}.tex"
BOOKLET_TEX = f"{BOOKLET_STEM}.tex"
OUTPUT_PDFS = (MAIN_PDF, BOOKLET_PDF)
KEEP_SUFFIXES = (".tex", ".pdf")

# --------------------------------------------------------------------------
# Content
# --------------------------------------------------------------------------

DEFAULT_TITLE = "Blue Line Ethics"
DEFAULT_SUBTITLE = "CS 377 at UIC, Fall 2026"
COVER_STOPS_LINE = "Forest Park to O'Hare"
COVER_NAME_LINE = "Name:"

# Two stops share a name across the two branches; label them so a reader
# flipping through the notebook can tell the pages apart.
BRANCH_SUFFIX = {
    ("Harlem", 0): "Forest Park branch",
    ("Harlem", 1): "O'Hare branch",
    ("Western", 0): "Forest Park branch",
    ("Western", 1): "O'Hare branch",
}

# --------------------------------------------------------------------------
# Page design
# --------------------------------------------------------------------------

CTA_BLUE = "00,161,222"     # the route color; used ONLY for the cover rules
DOT_GRAY = "0.62"           # xcolor gray level for the dot grid
RULE_GRAY = "0.55"          # xcolor gray level for every drawn line
HAIRLINE = "0.4pt"          # thickness of every drawn line

PAGE_W, PAGE_H = "5.5in", "8.5in"
MARGINS = "top=0.5in,bottom=0.45in,inner=0.55in,outer=0.45in"
HEAD_GEOMETRY = "headheight=22pt,headsep=14pt,footskip=12pt"

DEFAULT_DOT_PITCH = "0.2in"   # center-to-center spacing of the grid
DEFAULT_DOT_SIZE = "0.5pt"    # side of each square dot

COVER_RULE_THICKNESS = "9pt"      # the two full-bleed CTA-blue cover rules;
                                   # matches the 12px .blue-line rule on the
                                   # course website (12px * 0.75pt/px = 9pt)
HEADER_RULE_THICKNESS = HAIRLINE  # the rule under each page's header
NAMEBOX_WIDTH = "1.7in"           # write-in box in the cover's top-right corner
NAMEBOX_HEIGHT = "0.55in"
NAMEBOX_BORDER = HAIRLINE

PAGES_PER_STOP = 2
COVER_PAGES = 2               # front cover + blank back cover

# --------------------------------------------------------------------------
# LaTeX templates
# --------------------------------------------------------------------------

TEX_ESCAPES = {
    "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
    "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}", "\\": r"\textbackslash{}",
    "’": "'", "‘": "'", "–": "--", "—": "---",
}

PREAMBLE = r"""
\documentclass[10pt,twoside]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[scaled]{helvet}
\renewcommand{\familydefault}{\sfdefault}
\usepackage{xcolor}
\usepackage[paperwidth=%(pw)s,paperheight=%(ph)s,
            %(margins)s,%(head)s]{geometry}
\usepackage{fancyhdr}
\usepackage{pdfpages}

\definecolor{ctablue}{RGB}{%(blue)s}
\definecolor{dotgray}{gray}{%(dotgray)s}
\definecolor{rulegray}{gray}{%(rulegray)s}

\setlength{\parindent}{0pt}
\setlength{\parskip}{0pt}

\pagestyle{fancy}
\fancyhf{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

%% Header: stop name and page number, the number always on the outer edge,
%% over a hairline rule that runs the full text width.
\newcommand{\stopname}{}
\fancyhead[LE]{\headerline{\thepage}{\stopname}}
\fancyhead[RO]{\headerline{\stopname}{\thepage}}

\newcommand{\headerline}[2]{%%
  \parbox[b]{\textwidth}{%%
    \footnotesize\textbf{#1}\hfill
    \footnotesize\textbf{#2}\\[2pt]
    \textcolor{rulegray}{\rule{\textwidth}{%(headrule)s}}%%
  }%%
}

%% The book's one splash of CTA blue: a rule running the full width of the
%% *paper*, not the text block. It
%% starts at the left paper edge by backing out of the left margin, and is
%% set in a zero-width box so it never counts as an overfull line.
\newcommand{\fullrule}[1]{%%
  \par\noindent\makebox[0pt][l]{%%
    \hspace*{-\dimexpr 1in+\oddsidemargin+\hoffset\relax}%%
    \textcolor{ctablue}{\rule{\paperwidth}{#1}}}\par
}

%% Write-in box for the owner's name, anchored to the top-right corner.
\newcommand{\namebox}[1]{%%
  \par\noindent\hfill
  \fboxrule=%(nbborder)s\fboxsep=5pt
  \textcolor{rulegray}{\fbox{%%
    \parbox[t][%(nbheight)s][t]{%(nbwidth)s}{%%
      \scriptsize\textbf{#1}}}}\par
}

%% A dot grid filling the text block. Each row is a \leaders run of
%% pitch-wide boxes with a dot centered in each, so the columns line up
%% without needing an external drawing package.
\newlength{\dotpitch}\setlength{\dotpitch}{%(pitch)s}
\newlength{\dotsize}\setlength{\dotsize}{%(dotsize)s}
\makeatletter
\newlength{\dg@y}
\newcommand{\dg@mark}{\textcolor{dotgray}{\rule{\dotsize}{\dotsize}}}
\newcommand{\dg@row}{%%
  \hbox to \textwidth{%%
    \leaders\hbox to \dotpitch{\hss\dg@mark\hss}\hfil}%%
}
\newcommand{\dotpage}[1]{%%
  \renewcommand{\stopname}{#1}%%
  \noindent\vbox to \textheight{%%
    \setlength{\dg@y}{0pt}%%
    \@whiledim\dg@y<\dimexpr\textheight-\dotpitch\relax\do{%%
      \nointerlineskip\dg@row
      \vskip\dimexpr\dotpitch-\dotsize\relax
      \global\advance\dg@y by \dotpitch
    }%%
    \vss}%%
  \clearpage
}
\makeatother

\begin{document}
"""

COVER_TEMPLATE = r"""\thispagestyle{empty}
\namebox{%(nameline)s}
\vfill
\fullrule{%(rule)s}
\vspace{18pt}
\begin{center}
{\Huge\bfseries %(title)s}\\[10pt]
%(subtitle)s\end{center}
\vspace{12pt}
\fullrule{%(rule)s}
\vspace{22pt}
\begin{center}
%(lines)s
\end{center}
\vfill\null
\clearpage"""

COVER_SUBTITLE_TEMPLATE = "{\\large %s}\n"
COVER_LINE_TEMPLATE = "{\\footnotesize %s}"
COVER_LINE_SEP = "\\\\[10pt]\n"

BLANK_PAGE = r"\thispagestyle{empty}\null\clearpage"
STOP_HEAD_TEMPLATE = r"%s {\scriptsize\mdseries(%s)}"
DOTPAGE_TEMPLATE = r"\dotpage{%s}"
END_DOCUMENT = r"\end{document}"

BOOKLET_TEMPLATE = r"""
\documentclass[letterpaper,landscape]{article}
\usepackage[letterpaper,landscape,margin=0pt]{geometry}
\usepackage{pdfpages}
\begin{document}
\includepdf[pages=-,nup=2x1,signature=%(signature)d,landscape=false,
            noautoscale=false,delta=0pt 0pt]{%(src)s}
\end{document}
"""

# --------------------------------------------------------------------------
# Command line and messages
# --------------------------------------------------------------------------

PDFLATEX_CMD = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error"]
LATEX_PASSES = 2
LOG_TAIL_CHARS = 4000

HELP_STOPS = "CSV of stop names, one per row"
HELP_OUTDIR = "where the finished PDFs are written"
HELP_DOT_PITCH = "center-to-center dot spacing"
HELP_DOT_SIZE = "side length of each square dot"
HELP_TITLE = "cover title"
HELP_SUBTITLE = "cover subtitle"
HELP_SIGNATURE = ("pages per folded signature (multiple of 4); "
                  "0 = one signature for the whole book")
HELP_KEEP_TEX = "leave the intermediate build files in place"

ERR_PAGE_COUNT = "{n} pages is not a multiple of 4; add or remove a cover page."
ERR_SIGNATURE = "--signature must be a multiple of 4"
ERR_LATEX = "pdflatex failed on {name}"
MSG_SUMMARY = "{stops} stops -> {pages} pages ({sheets} folded sheets, signature={sig})"
MSG_OUTPUT = "   {path}"


def tex_escape(s: str) -> str:
    return "".join(TEX_ESCAPES.get(c, c) for c in s)


def load_stops(path: Path):
    with path.open(newline="", encoding="utf-8") as fh:
        names = [row[0].strip() for row in csv.reader(fh) if row and row[0].strip()]
    seen = {}
    stops = []
    for name in names:
        n = seen.get(name, 0)
        seen[name] = n + 1
        stops.append((name, BRANCH_SUFFIX.get((name, n))))
    return stops


def cover_page(title, subtitle, lines, nameline):
    return COVER_TEMPLATE % {
        "title": tex_escape(title),
        "subtitle": COVER_SUBTITLE_TEMPLATE % tex_escape(subtitle) if subtitle else "",
        "lines": COVER_LINE_SEP.join(COVER_LINE_TEMPLATE % tex_escape(line)
                                     for line in lines),
        "nameline": tex_escape(nameline),
        "rule": COVER_RULE_THICKNESS,
    }


def build_main_tex(stops, pitch, dotsize, title, subtitle):
    out = [PREAMBLE % {"pw": PAGE_W, "ph": PAGE_H, "margins": MARGINS,
                       "head": HEAD_GEOMETRY, "blue": CTA_BLUE,
                       "dotgray": DOT_GRAY, "pitch": pitch, "dotsize": dotsize,
                       "nbwidth": NAMEBOX_WIDTH, "nbheight": NAMEBOX_HEIGHT,
                       "nbborder": NAMEBOX_BORDER, "rulegray": RULE_GRAY,
                       "headrule": HEADER_RULE_THICKNESS}]
    out.append(cover_page(title, subtitle,
                          [COVER_STOPS_LINE.format(n=len(stops))],
                          COVER_NAME_LINE))
    for name, branch in stops:
        head = tex_escape(name)
        if branch:
            head = STOP_HEAD_TEMPLATE % (head, tex_escape(branch))
        out.extend([DOTPAGE_TEMPLATE % head] * PAGES_PER_STOP)
    out.append(BLANK_PAGE)  # back cover
    out.append(END_DOCUMENT)
    return "\n".join(out)


def build_booklet_tex(src_pdf: str, signature: int):
    return BOOKLET_TEMPLATE % {"signature": signature, "src": src_pdf}


def run_latex(tex_path: Path, workdir: Path):
    for _ in range(LATEX_PASSES):
        proc = subprocess.run(PDFLATEX_CMD + [tex_path.name],
                              cwd=workdir, capture_output=True, text=True)
        if proc.returncode != 0:
            sys.stderr.write(proc.stdout[-LOG_TAIL_CHARS:])
            raise SystemExit(ERR_LATEX.format(name=tex_path.name))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stops", type=Path, default=STOPS_CSV, help=HELP_STOPS)
    ap.add_argument("--outdir", type=Path, default=HERE, help=HELP_OUTDIR)
    ap.add_argument("--dot-pitch", default=DEFAULT_DOT_PITCH, help=HELP_DOT_PITCH)
    ap.add_argument("--dot-size", default=DEFAULT_DOT_SIZE, help=HELP_DOT_SIZE)
    ap.add_argument("--title", default=DEFAULT_TITLE, help=HELP_TITLE)
    ap.add_argument("--subtitle", default=DEFAULT_SUBTITLE, help=HELP_SUBTITLE)
    ap.add_argument("--signature", type=int, default=0, help=HELP_SIGNATURE)
    ap.add_argument("--keep-tex", action="store_true", help=HELP_KEEP_TEX)
    args = ap.parse_args()

    stops = load_stops(args.stops)
    npages = PAGES_PER_STOP * len(stops) + COVER_PAGES
    if npages % 4:
        raise SystemExit(ERR_PAGE_COUNT.format(n=npages))
    signature = args.signature or npages
    if signature % 4:
        raise SystemExit(ERR_SIGNATURE)

    build = args.outdir / BUILD_DIRNAME
    build.mkdir(parents=True, exist_ok=True)

    main_tex = build / MAIN_TEX
    main_tex.write_text(build_main_tex(stops, args.dot_pitch, args.dot_size,
                                       args.title, args.subtitle),
                        encoding="utf-8")
    run_latex(main_tex, build)

    bk_tex = build / BOOKLET_TEX
    bk_tex.write_text(build_booklet_tex(MAIN_PDF, signature), encoding="utf-8")
    run_latex(bk_tex, build)

    for name in OUTPUT_PDFS:
        shutil.copy(build / name, args.outdir / name)

    if not args.keep_tex:
        for f in build.iterdir():
            if f.suffix not in KEEP_SUFFIXES:
                f.unlink()

    print(MSG_SUMMARY.format(stops=len(stops), pages=npages,
                             sheets=npages // 4, sig=signature))
    for name in OUTPUT_PDFS:
        print(MSG_OUTPUT.format(path=args.outdir / name))


if __name__ == "__main__":
    main()
